### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ghost** [VQATRICKER/QUANGANH#1]
NOOB COPY MY PROJECT :))

**Comment by VQATRICKER** [comment]
kệ bố tao thằng lồn

Vào Th 3, 17 thg 5, 2022 vào lúc 15:47 zxcr9999 ***@***.***>
đã viết:

**Comment by VQATRICKER** [comment]
kệ bố tai thằng mặt lồn

**Comment by ghost** [comment]
> kệ bố tai thằng mặt lồn

đúng là các bác trẻ trâu tricker, hãy cố học tập đừng copy như một thằng ngu :))
